server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: article-service
          uri: http://article-service
          predicates:
            - Path=/article-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: articleCircuitBreaker
                fallbackUri: forward:/article-fallback

        - id: author-service
          uri: http://author-service
          predicates:
            - Path=/author-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: authorCircuitBreaker
                fallbackUri: forward:/author-fallback
        - id: story-service
          uri: http://story-service
          predicates:
            - Path=/story-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: storyCircuitBreaker
                fallbackUri: forward:/story-fallback
  zipkin:
    baseurl: http://172.29.3.101:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: EUREKA_URL:http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
resilience4j:
  circuitbreaker:
    instances:
      catalogCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}
